update

diff --git a/.github/workflows/create-repo.yml b/.github/workflows/create-repo.yml
--- a/.github/workflows/create-repo.yml
+++ b/.github/workflows/create-repo.yml
@@ -121,18 +121,18 @@ jobs:
           # git add workflow_runs.json
           # git commit -m "Update workflow_runs.json with file_count and latest_commit_id"
           # git push https://code2docs-ai:${{ secrets.MY_PAT }}@github.com/${{ github.repository }}.git main
-          
+
           echo "${{ github.event.inputs.serverEndPoint }}"/github/update/repo-versions
           echo "$file_count"
-          curl --fail -k -X POST ${{ github.event.inputs.serverEndPoint }}/github/update/repo-versions \
+          curl --fail -k -X POST -L ${{ github.event.inputs.serverEndPoint }}/github/update/repo-versions \
           -H "Content-Type: application/json" \
           -d '{
                 "id": "${{ github.event.inputs.repoVersionId }}",
                 "workflow_id": "${{ github.run_id }}",
                 "status": "in_progress(parse-repo)",
-                "file_count": "${{file_count}}",
+                "file_count": "$file_count",
                 "current_commit_id": "$latest_commit_id"
-              }' || exit 1
+              }' || echo "API call failed" && exit 1
 
       - name: Run aise-cli
         run: |
